server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/goods?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#    encoding: UTF-8
#    mode: LEGACYHTML5
#    servlet:
#      content-type: text/html

  thymeleaf:
    cache: false
    prefix: "classpath:/templates/"
    mode: HTML
    suffix: .html
  resources:
      static-locations: [classpath:/static,classpath:/public,classpath:/templates]
  mvc:
    static-path-pattern: /**




mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper./*Mapper.xml
  type-aliases-package: com.yuan.entity

logging:
  level:
    com.yuan.mapper: trace
